# official base image
FROM node:17-alpine

# RUN apk add --no-cache libc6-compat
USER node

# set work directory
WORKDIR /home/node/

# set environment variables
ENV PATH /home/node/node_modules/.bin:$PATH

# copy files
COPY --chown=node:node package*.json ./
RUN npm install --silent
COPY --chown=node:node . ./
