# official base image
FROM node:18-alpine

USER node

# set work directory
WORKDIR /home/node

# set environment variables
ENV PATH /home/node/node_modules/.bin:$PATH

# copy files
COPY --chown=node:node package*.json ./
RUN npm install
COPY --chown=node:node . ./
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
