# official base image
FROM node:18-alpine as app-frontend

USER node

# set work directory
ENV HOME=/home/node/
RUN mkdir $HOME/build
WORKDIR $HOME

# set environment variables
ENV PATH $HOME/node_modules/.bin:$PATH

# copy files
COPY --chown=node:node package*.json $HOME
RUN npm ci --production
COPY . $HOME

# nginx topping
RUN npm run build

FROM nginx:latest

COPY --from=app-frontend /home/node/build/ /var/www/frontend
