# Generated by Django 3.1.2 on 2020-11-16 09:28

import apps.homework.storage
import apps.teaching.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureresource',
            name='file',
            field=models.FileField(storage=apps.homework.storage.OverwriteStorage(), upload_to=apps.teaching.helpers.get_lecture_rsc_path),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(storage=apps.homework.storage.OverwriteStorage(), upload_to=apps.teaching.helpers.get_lesson_rsc_path),
        ),
    ]
