# Generated by Django 3.1.2 on 2020-11-18 14:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20201116_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title'),
        ),
    ]
