# Generated by Django 3.1.2 on 2020-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_auto_20201118_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureresource',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='Gibt an ob die Resource auf der Seite aufgelistet wird.'),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Gibt an ob die Resource per Link heruntergeladen werden kann.'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='Gibt an ob die Resource auf der Seite aufgelistet wird.'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Gibt an ob die Resource per Link heruntergeladen werden kann.'),
        ),
    ]
