# Generated by Django 3.1.2 on 2020-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20201118_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureresource',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='Listed on website'),
        ),
        migrations.AlterField(
            model_name='lectureresource',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Downloadable via link'),
        ),
    ]
