# Generated by Django 3.1.2 on 2020-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_auto_20201118_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='Listed on website'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Downloadable via link'),
        ),
    ]
