# Generated by Django 3.1.2 on 2020-11-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_merge_20201119_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureresource',
            name='listed',
        ),
        migrations.RemoveField(
            model_name='lectureresource',
            name='public',
        ),
        migrations.RemoveField(
            model_name='lessonresource',
            name='listed',
        ),
        migrations.RemoveField(
            model_name='lessonresource',
            name='public',
        ),
    ]
