# Generated by Django 3.1.2 on 2020-11-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0010_auto_20201123_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureresource',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teaching.lecture'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teaching.lesson'),
        ),
    ]
