# Generated by Django 3.1.2 on 2020-12-18 16:15

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0011_auto_20201125_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_1_0', models.PositiveIntegerField(verbose_name='Points needed for Grade 1.0')),
                ('grade_1_3', models.PositiveIntegerField(verbose_name='Points needed for Grade 1.3')),
                ('grade_1_7', models.PositiveIntegerField(verbose_name='Points needed for Grade 1.7')),
                ('grade_2_0', models.PositiveIntegerField(verbose_name='Points needed for Grade 2.0')),
                ('grade_2_3', models.PositiveIntegerField(verbose_name='Points needed for Grade 2.3')),
                ('grade_2_7', models.PositiveIntegerField(verbose_name='Points needed for Grade 2.7')),
                ('grade_3_0', models.PositiveIntegerField(verbose_name='Points needed for Grade 3.0')),
                ('grade_3_3', models.PositiveIntegerField(verbose_name='Points needed for Grade 3.3')),
                ('grade_3_7', models.PositiveIntegerField(verbose_name='Points needed for Grade 3.7')),
                ('grade_4_0', models.PositiveIntegerField(verbose_name='Points needed for Grade 4.0')),
                ('grade_5_0', models.PositiveIntegerField(default=0, verbose_name='Points needed for Grade 4.0')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['title'], 'verbose_name': 'Vorlesung', 'verbose_name_plural': 'Vorlesungen'},
        ),
    ]
