# Generated by Django 3.1.2 on 2020-12-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0013_lecture_grading_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingscale',
            options={'verbose_name': 'Benotung'},
        ),
    ]
