# Generated by Django 3.1.2 on 2020-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0014_auto_20201218_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingscale',
            options={'verbose_name': 'Benotungsskala', 'verbose_name_plural': 'Benotungsskalen'},
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_5_0',
            field=models.PositiveIntegerField(default=0, verbose_name='Points needed for Grade 5.0'),
        ),
    ]
