# Generated by Django 3.1.4 on 2020-12-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0015_auto_20201218_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_1_0',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 1.0'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_1_3',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 1.3'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_1_7',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 1.7'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_2_0',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 2.0'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_2_3',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 2.3'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_2_7',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 2.7'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_3_0',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 3.0'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_3_3',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 3.3'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_3_7',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 3.7'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_4_0',
            field=models.PositiveIntegerField(verbose_name='Punkte nötig für 4.0'),
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='grade_5_0',
            field=models.PositiveIntegerField(default=0, verbose_name='Punkte nötig für 5.0'),
        ),
    ]
