version: '3.7'
volumes:
    volume_db:
    volume_static:
    volume_media:
    volume_redis:
    volume_rq:
services:
    web:
        build:
            context: ./server
        depends_on:
            - db
            - redis
        environment:
            POSTGRES_HOST: homework-checker_db
        restart: always
        volumes:
            - volume_static:/home/app/web/staticfiles:rw
            - volume_media:/home/app/web/mediafiles:rw
    db:
        image: postgres:12-alpine
        expose:
            - 5432
        restart: always
        volumes:
         - volume_db:/var/lib/postgresql/data
    redis:
        image: redis:6-alpine
        expose:
            - 6379
        restart: always
        volumes:
            - volume_redis:/data
    rq:
        command: python manage.py rqworker default
        build:
            context: ./server
        environment:
            POSTGRES_HOST: app-db
        restart: always
        volumes:
            - volume_rq:/rqdata
            - volume_media:/home/app/web/mediafiles
            - $PODMAN_PATH:/var/run/podman.sock
        depends_on:
            - redis
            - db
    client:
        build:
            context: ./client
        restart: always
        volumes:
            - ./client/node_modules:/app/node_modules
        depends_on:
          - web
