version: '3.7'
volumes:
    app-db:
    static_volume:
    media_volume:
    redisdata:
    rqdata:
services:
    app-web:
        build:
            context: ./server
        container_name: app-web
        depends_on:
            - app-db
            - app-redis
        environment:
            POSTGRES_HOST: app-db
        restart: always
        volumes:
            - static_volume:/home/app/web/staticfiles:rw
            - media_volume:/home/app/web/mediafiles:rw
    app-db:
        container_name: app-db
        image: postgres:12-alpine
        expose:
            - 5432
        restart: always
        volumes:
         - app-db:/var/lib/postgresql/data
    app-redis:
        container_name: app-redis
        image: redis:6-alpine
        expose:
            - 6379
        restart: always
        volumes:
            - redisdata:/data
    app-rq:
        command: python manage.py rqworker default
        build:
            context: ./server
        container_name: app-rq
        environment:
            POSTGRES_HOST: app-db
        restart: always
        volumes:
            - rqdata:/rqdata
            - media_volume:/home/app/web/mediafiles
            - $PODMAN_PATH:/var/run/podman.sock
        depends_on:
            - app-redis
            - app-db
    app-client:
        container_name: app-client
        build:
            context: ./client
        restart: always
        volumes:
            - ./client/node_modules:/app/node_modules
        depends_on:
          - app-web
