# Generated by Django 3.2.13 on 2022-07-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('identifier',), 'verbose_name': 'student'},
        ),
    ]
