# Generated by Django 3.1.2 on 2020-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='identifier'),
        ),
    ]
