# Generated by Django 3.1.2 on 2020-11-23 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201123_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only digit characters.')], verbose_name='identifier'),
        ),
    ]
