# Generated by Django 3.1.4 on 2021-03-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201126_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('identifier',)},
        ),
    ]
