# Generated by Django 3.1.2 on 2020-10-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20201002_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
    ]
