FROM python:3.8.5-slim-buster

RUN mkdir -p /home/app/
#RUN groupadd -r app && useradd -r -g app app

ENV HOME=/home/app/
ENV APP_HOME=/home/app/web/
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONHASHSEED random

ENV POETRY_VERSION 1.0.10
ENV POETRY_VIRTUALENVS_CREATE false

ENV DJANGO_SETTINGS_MODULE "config.settings.dev"

# System dependencies
RUN apt-get update \
  && apt-get -y install gcc postgresql netcat \
  && apt-get clean

# Python dependencies
RUN pip install "poetry==$POETRY_VERSION"
COPY poetry.lock pyproject.toml $APP_HOME
RUN poetry install --no-interaction --no-ansi

COPY ./entrypoint.dev.sh $APP_HOME
COPY . $APP_HOME

#RUN chown -R app:app $APP_HOME

