# official base image
FROM python:3.9-slim-buster

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONHASHSEED random

ENV POETRY_VERSION 1.0.10
ENV POETRY_VIRTUALENVS_CREATE false

ENV DJANGO_SETTINGS_MODULE config.settings.development

# set work directory
WORKDIR /home/app/web/
RUN mkdir -p ./staticfiles
RUN mkdir -p ./mediafiles

# system dependencies
RUN apt-get update \
  && apt-get -y install gcc postgresql netcat docker \
  && apt-get clean

# python dependencies
RUN pip install "poetry==$POETRY_VERSION"
COPY poetry.lock pyproject.toml ./
RUN poetry install --no-interaction --no-ansi

# copy files
COPY ./entrypoint.sh ./
COPY . ./

ENTRYPOINT ["/home/app/web/entrypoint.sh"]
