# Generated by Django 3.1.4 on 2021-03-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='content',
        ),
    ]
