# Generated by Django 3.1.7 on 2021-03-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='rated',
        ),
        migrations.AddField(
            model_name='exercise',
            name='graded',
            field=models.BooleanField(default=False, verbose_name='Graded'),
        ),
    ]
