# Generated by Django 3.1.2 on 2020-11-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
