# Generated by Django 3.1.7 on 2021-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20210324_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
