# Generated by Django 3.1.2 on 2020-11-15 09:26

import apps.homework.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0002_auto_20201114_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='allowed_extensions',
            field=models.TextField(blank=True, verbose_name='Erlaubte Dateiendungen. Wenn nicht gesetzt, sind alle Dateiendungen erlaubt.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='allowed_mimetypes',
            field=models.TextField(blank=True, verbose_name='Erlaubte Dateitypen. Wenn nicht gesetzt, sind alle Dateitypen erlaubt.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_upload_size',
            field=models.PositiveIntegerField(default=5000, verbose_name='Maximale Upload Größe in Bytes'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='min_upload_size',
            field=models.PositiveIntegerField(default=30, verbose_name='Maximale Upload Größe in Bytes'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Maximale Testlaufzeit in Sekunden'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default=1, upload_to=apps.homework.helpers.get_submission_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='file_hash',
            field=models.CharField(default=1, editable=False, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('file_hash', 'user')},
        ),
    ]
