# Generated by Django 3.1.2 on 2020-11-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20201115_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='allowed_extensions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='allowed_mimetypes',
        ),
        migrations.AddField(
            model_name='exercise',
            name='programming_language',
            field=models.CharField(choices=[('ph', 'Python'), ('r', 'R')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_hash',
            field=models.CharField(max_length=40),
        ),
    ]
