# Generated by Django 3.1.7 on 2021-04-04 13:21

import autoslug.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_exercise_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='title'),
        ),
    ]
