# Generated by Django 3.1.2 on 2020-11-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20201116_0227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
