# Generated by Django 3.2.13 on 2022-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_auto_20220530_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='runtime_environment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
