# Generated by Django 3.1.2 on 2020-11-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_auto_20201117_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='programming_language',
            field=models.CharField(choices=[('py', 'Python'), ('r', 'R')], max_length=2),
        ),
    ]
