# Generated by Django 3.1.2 on 2020-11-18 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0009_auto_20201117_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('file_hash', 'user', 'exercise')},
        ),
    ]
