# Generated by Django 3.1.2 on 2020-11-18 14:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_auto_20201118_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title'),
        ),
    ]
