# Generated by Django 3.1.2 on 2020-11-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0012_auto_20201118_1645'),
        ('homework', '0012_auto_20201118_1558'),
    ]

    operations = [
    ]
