# Generated by Django 3.1.2 on 2020-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_merge_20201118_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseresource',
            name='public',
        ),
        migrations.AddField(
            model_name='exerciseresource',
            name='loaded',
            field=models.BooleanField(default=True, verbose_name='Loaded into test environment'),
        ),
    ]
