# Generated by Django 3.1.2 on 2020-11-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_auto_20201118_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseresource',
            options={'verbose_name': 'Übungsmaterial', 'verbose_name_plural': 'Testmaterialien'},
        ),
    ]
