# Generated by Django 3.1.2 on 2020-11-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_auto_20201119_1306'),
        ('homework', '0015_auto_20201118_1911'),
    ]

    operations = [
    ]
