# Generated by Django 3.1.2 on 2020-11-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_merge_20201119_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseresource',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exerciseresource',
            name='loaded',
        ),
        migrations.RemoveField(
            model_name='exerciseresource',
            name='title',
        ),
    ]
