# Generated by Django 3.1.4 on 2020-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0017_auto_20201125_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rated',
            field=models.BooleanField(default=True, verbose_name='Fließt in Note ein'),
        ),
    ]
