# Generated by Django 3.1.4 on 2021-03-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0017_auto_20210314_1556'),
        ('homework', '0018_exercise_rated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='exerciseresource',
            options={},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.lesson'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='max_score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='max_upload_size',
            field=models.PositiveIntegerField(default=5000, verbose_name='Maximal byte size'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='min_upload_size',
            field=models.PositiveIntegerField(default=30, verbose_name='Minimal byte size'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rated',
            field=models.BooleanField(default=True, verbose_name='Graded'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
